### ISSUE TITLE
Requesting app to be added to F-Droid

### ISSUE THREAD

**Issue by ShapeShifter499** [emrsmsrli/Caffeine#1]
I'd like to submit a request to the folks behind the F-Droid app market and their repository to add this app but I need to get your support first. It's it alright for me to ask that this app be added to F-Droid?

In case you don't know what F-Droid is:  F-Droid is a Google Play Store alternative that works like a package manager letting you add all sorts of repositories. Their official F-Droid repository contains various FOSS apps that they build from source when it's updated and host.

**Comment by emrsmsrli** [comment]
Hi @ShapeShifter499! Firstly, thanks for your attention. Though I already know that F-Droid is, I haven't used it before and I don't know the procedure to upload an app to the platform. I would be very much appreciated if you help me how to do it. You have my full support on the matter.

Thanks again, have a good day!

**Comment by ShapeShifter499** [comment]
I'll make a request ticket over at F-Droid and link it here when it's up. I'll do that in a few hours or so.

**Comment by ShapeShifter499** [comment]
@emrsmsrli I have a update, I thought to double check if there were any similar apps already in the F-Droid repository and I did find https://github.com/otaconix/caffeinetile. It's missing the timer settings though, it's either on or off.

**Comment by emrsmsrli** [comment]
@ShapeShifter499 There are many applications like this, of course. It is a copy of the original Caffeine app bundled with the [LineageOS](https://lineageos.org/).
