### ISSUE TITLE
Failing to keep device awake

### ISSUE THREAD

**Issue by ShapeShifter499** [emrsmsrli/Caffeine#2]
I'm using this on a Motorola X Pure running the latest stock rom of Nougat 7.0. I'd like to keep the phone awake when it's plugged in and listening to music but not always. 

I installed this app, set up the quick tile, and triple tapped till I saw the infinity symbol and a "filled" white cup. After a couple of minutes my device goes to sleep and I have to to unlock it even though I was certain I activated this caffine app.

**Comment by emrsmsrli** [comment]
Hi @ShapeShifter499 !

Can you give me the logcat of your device after the device goes to sleep when Caffeine is active? 

If you don't know how to gather logcat: 

- If you have a terminal app on your device, open it and write `logcat > /sdcard/log.txt`. Then upload the log.txt in your internal storage folder here.
- If you have Android SDK installed on your computer, you can go to `%sdkfolder%/platform-tools/`. Then open a command line in the folder and execute command `adb.exe logcat > log.txt`. Then upload the log.txt here. If you don't have SDK installed and still want to use this option, you can download platform tools [here](https://developer.android.com/studio/releases/platform-tools.html).

Thanks!

**Comment by ShapeShifter499** [comment]
I can do this later today.

**Comment by ShapeShifter499** [comment]
@emrsmsrli I started logcat and then started caffine on the infinity setting. I waited untill the device went to sleep, then I  unlocked it and stopped the log.  Attached is a log from this. 
[caffeine.txt](https://github.com/emrsmsrli/Caffeine/files/1502970/caffeine.txt)

**Comment by emrsmsrli** [comment]
@ShapeShifter499 You have to run the logcat AFTER device goes to sleep. You can unlock your device and try `logcat -d > /sdcard/log.txt`. Thanks!

Edit: Don't forget the `-d` parameter!
