### ISSUE TITLE
Crashes with IllegalArgumentException

### ISSUE THREAD

**Issue by ghost** [emrsmsrli/Caffeine#6]
The app randomly crashes. Here's the log:

```
07-29 18:25:31.490 E/AndroidRuntime(32608): java.lang.IllegalArgumentException: Service not registered: tr.edu.iyte.caffeine.CaffeineTileService$e@fa762f6
07-29 18:25:31.490 E/AndroidRuntime(32608): 	at tr.edu.iyte.caffeine.CaffeineTileService.onStopListening(Unknown Source:8)
```

I'm not sure how to reproduce it, it seems to be random (it even crashes sometimes when Caffeine is off).

**Comment by emrsmsrli** [comment]
Should be fixed

**Comment by ghost** [comment]
Nope, still giving the same error.

**Comment by emrsmsrli** [comment]
Unfortunately, I cannot pinpoint the issue without sophisticated error reporting libraries. I removed the proguard optimizations so exceptions should be a little more clear. Can you update the app and continue using it, so I can understand what the problem is? Thanks.

**Comment by ghost** [comment]
I haven't had a crash since the latest update (been about 26 minutes since I updated it, according to Google Play). So that may have fixed it. I'll leave the issue open for like a day to be sure, but it looks like it may be solved.

**Comment by ghost** [comment]
It still hasn't crashed, so I'm guessing it's solved.
