### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by IzzySoft** [emrsmsrli/Caffeine#8]
Could you please clarify what license this project uses?

**Comment by emrsmsrli** [comment]
Please see [this.](https://github.com/emrsmsrli/Caffeine/blob/master/LICENSE)

**Comment by IzzySoft** [comment]
Thanks! Somehow I missed it before (maybe because it was just added? 🤣 ) Good thing 😃

**Comment by emrsmsrli** [comment]
Yeah I just added it. Sorry about that. :)

**Comment by IzzySoft** [comment]
No problem, and no reason to be sorry – I perfectly got the joke (and understood it as it is exactly the kind of thing I would do) 🤣
